apiVersion: apps/v1
kind: Deployment
metadata:
  name: springserver
spec:
  selector:
    matchLabels:
      app: springserver
  template:
    metadata:
      labels:
        app: springserver
    spec:
      containers:
        - name: springserver
          image: springserver
          ports:
            - containerPort: 8080