apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: jaksonlima/gitops
  newTag: newTag
- name: springserver
  newName: jaksonsneider/gitops
  newTag: d24c294097815a09a13bc439595e92375fb0f770
